### ISSUE TITLE
error saving PyTorch model

### ISSUE THREAD

**Issue by bobertlo** [iterative/mlem#281]
A user on discord shared this example that gave an error and I was able to reproduce. This seems to be how you are supposed to call it but it is unclear if we are doing something wrong?? I am not super familiar with the pertained models in torch vision but looking at the source there doesn't seem to be anything special going on there and I reproduced it with a model I have also to be sure.

I am using the 0.2.2 release installed with pip. I am on the nightly PyTorch but installed stable and reproduced it also. 

This is the provided example code:

```
from mlem.api import save
from torchvision import models

model = models.resnet18(pretrained=True)
save(model, 'resnet18')
```

This is the error with mlem 0.2.2 installed with pip:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/metadata.py", line 34, in get_object_metadata
    return MlemData.from_data(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/objects.py", line 675, in from_data
    data_type = DataType.create(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/data_type.py", line 74, in create
    return DataAnalyzer.analyze(obj, **kwargs).bind(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/hooks.py", line 107, in analyze
    return cls._find_hook(obj).process(obj, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/hooks.py", line 135, in _find_hook
    raise HookNotFound(
mlem.core.errors.HookNotFound: No suitable DataHook for object of type "ResNet". Registered hooks: [<class 'mlem.core.data_type.PrimitiveType'>, <class 'mlem.core.data_type.OrderedCollectionHook'>, <class 'mlem.core.data_type.DictType'>, <class 'mlem.contrib.torch.TorchTensorDataType'>, <class 'mlem.contrib.numpy.NumpyNumberType'>, <class 'mlem.contrib.numpy.NumpyNdarrayType'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/metadata.py", line 96, in save
    meta = get_object_metadata(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/metadata.py", line 38, in get_object_metadata
    return MlemModel.from_obj(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/objects.py", line 611, in from_obj
    mt = ModelAnalyzer.analyze(model, sample_data=sample_data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/model.py", line 298, in analyze
    return super().analyze(obj, sample_data=sample_data, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/hooks.py", line 107, in analyze
    return cls._find_hook(obj).process(obj, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/contrib/torch.py", line 155, in process
    "torch_predict": Signature.from_method(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/mlem/core/model.py", line 163, in from_method
    result = method(**call_kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: ResNet.forward() got an unexpected keyword argument 'data'
```

**Comment by bobertlo** [comment]
Could this fix maybe get tagged in a release? It seems like PyTorch wouldn't be working for anyone right now.
