### ISSUE TITLE
Place friendly error message

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#521]
Right now, if this is called without `--tb`, the error will simply say `ValueError: []`. I think we should print something understandable or even just print `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/auth` as well.

```shell
(mlem) get-started (main) $ mlem --tb deploy run --load chatgpt_app.mlem --model chatgpt                                                         3.531s
⏳️ Loading model from chatgpt.mlem
⏳️ Loading deployment from chatgpt_app.mlem
🛠 Creating docker image for heroku
  🛠 Building MLEM wheel file...
  💼 Adding model files...
  🛠 Generating dockerfile...
  💼 Adding sources...
  💼 Generating requirements file...
  🛠 Building docker image registry.heroku.com/mlem-chatgpt/web...
Traceback (most recent call last):
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/auth

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/heroku/build.py", line 37, in login
    self._login(self.host, client, "_", password)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/docker/base.py", line 185, in _login
    res = client.login(
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/client.py", line 199, in login
    return self.api.login(*args, **kwargs)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/api/daemon.py", line 152, in login
    return self._result(response, json=True)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/auth: Internal Server Error ("Get "https://registry.heroku.com/v2/": no basic auth credentials")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/bin/mlem", line 8, in <module>
    sys.exit(app())
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/aguschin/Git/iterative/mlem/mlem/cli/main.py", line 475, in inner
    f(*iargs, **ikwargs)
  File "/Users/aguschin/Git/iterative/mlem/mlem/cli/main.py", line 340, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem/mlem/cli/deployment.py", line 81, in deploy_run_callback
    deploy(
  File "/Users/aguschin/Git/iterative/mlem/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem/mlem/api/commands.py", line 482, in deploy
    deploy_meta.deploy(model_meta)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/heroku/meta.py", line 97, in deploy
    state.image = build_heroku_docker(
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/heroku/build.py", line 56, in build_heroku_docker
    return build_model_image(
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/docker/helpers.py", line 31, in build_model_image
    builder.build(model)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/docker/base.py", line 564, in build
    return self.build_image(tempdir)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/docker/utils.py", line 146, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/docker/base.py", line 573, in build_image
    self.image.registry.login(client)
  File "/Users/aguschin/Git/iterative/mlem/mlem/contrib/heroku/build.py", line 39, in login
    raise ValueError([]) from e
ValueError: []
```

**Comment by aguschin** [comment]
UPD: the problem was in the way I removed shell var. Initially, I both did `heroku login` and set `HEROKU_API_KEY`. Getting error messages that I need to use a single auth method, I decided to unset shell var with `export HEROKU_API_KEY=`. That gave me a problem, apparently. After `unset HEROKU_API_KEY` the problem has gone.
