### ISSUE TITLE
Can't build docker image if requirements aren't installed

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#550]
Can't build docker image if requirements aren't installed
```shell
$ mlem deploy run flyio fly.mlem -m ../mlem/emoji/lyrics2emoji --app_name hat
💾 Saving deployment to fly.mlem
⏳️ Loading model from ../mlem/emoji/lyrics2emoji.mlem
2022-12-28 15:53:50,224 [WARNING] mlem.utils.module: Fail to determine package name for module 'spacy', using module name instead. If that's incorrect, fix metadata manually, either in `.mlem` file or in your MLEM Python object.
2022-12-28 15:53:50,375 [WARNING] mlem.utils.module: Fail to determine package name for module 'transformers', using module name instead. If that's incorrect, fix metadata manually, either in `.mlem` file or in your MLEM Python object.
❌ Unexpected error: No module named 'transformers'
Use the --tb or --traceback option to include the traceback in the output
Please report it here: <https://github.com/iterative/mlem/issues>

$ yq eval .requirements ../mlem/emoji/lyrics2emoji.mlem
- module: spacy
  version: 3.4.4
- is_package: false
  module: __main__
  name: __main__
  source64zip: eJx1VMFu2zgQvesrCF1EdRVus0cDPrRJLwWaFtjsyQgEmhzHTCiSy6Fiu1+/Q0pW4rRr2JI5fDOcefOGZgg+JubGIZyYROZCZSZTkE6Tgb5Bn23JR7WvKr1ja7KKCFL3Cl94Lf7UMklB/8XRYt0SROxpl7fV2ReDVKeqcjaQc1kI6wlRg+uVj9AfYNvjQL6Vhh1TFqTrExwTz492VTH6aK/Im2JMxmI7+KiRrJuyyp/kn8GJjFhMOx8nMzMuR1k2zG6GB489cz5lwKb5dPuj6Vhzc/P97mv+c/vlPr9+/HN3c988FO/pmU+hwxvWiCdvHC/ZTIlFSGN0BVFVM66+3xucnJR3SRpH/I5OpVEm413HQgTKxOQFdox6kHFPGZEtoq5CNC7x9/QQa9Uu+oGlKB1StQNEZDP1twaTsZ8hpvtcqvkJsXtj/OY1WMrwvEdp/sZD5PA9pUcnGAeaN7qAtgS62kqEK0qSXrppqyFHvAhTzvglRP0/Ic4iICjBvQJE/iLtCCuGKc5aAKcoqO6NC2Omdsl/gnYz/0SSQx9x3YTUTI3xY5pcSp78w4eLUBfNm6DCSkz93mhNYsUkEwj8dwT4Cfxju7m6fhAaklR73ooySfSOgHsZgF937OqayoHBP5kehi1obdxjFqwLgnqrKJqjH6eRkSHYE7dy2GrJjquL+o+ihLiTA2BLyjgaXF+Xvk+Nx2eSRHRiIHaNQhGkiQeDcBaBIlU56NEMxspoEs1i4XhnHA2x9QiYino75ijwxPELKJr5PO1vMsmgiaQlmIFc0C9H8PdVd3PEC44tiSBXX8AojPVq8zayiPKF2tQKGR+pk4kT5W71sFmtiPmHdq6jCN8Ska9T0bHnpZJlW+cprKvzpZCLySP/fqAEBmvoqNVyU8wckftvKXtuX++f17P+WJ/9skzybWOII5KQU8Dnna4w0DKw1K3ZdnGBLOGo1Hdl1l+JVgtsC9YSu08Xq3lPWsvSHthBnupXvQwWBhKcOesDieRqmdy84pdnday2pyytv0qj6o5AQ7DQ56t/Xf/t/IENIxH06Jl3dNJ/os0lFQ==
  type: custom
- module: transformers
  version: 4.25.1
- module: sklearn
  package_name: scikit-learn
  version: 1.1.1
- module: pandas
  version: 1.5.2
- module: numpy
  version: 1.23.5
- extra_index: https://download.pytorch.org/whl/cpu
  module: torch
  version: 1.13.0
```

long tb

```python
$ mlem --tb deploy run flyio fly.mlem -m ../../mlem/emoji/lyrics2emoji --app_name hat                                  92ms
💾 Saving deployment to fly.mlem
⏳️ Loading model from ../../mlem/emoji/lyrics2emoji.mlem
2022-12-28 16:08:08,117 [WARNING] mlem.utils.module: Fail to determine package name for module 'spacy', using module name instead. If that's incorrect, fix metadata manually, either in `.mlem` file or in your MLEM Python object.
2022-12-28 16:08:08,261 [WARNING] mlem.utils.module: Fail to determine package name for module 'transformers', using module name instead. If that's incorrect, fix metadata manually, either in `.mlem` file or in your MLEM Python object.
Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/bin/mlem", line 8, in <module>
    sys.exit(app())
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/cli/main.py", line 174, in invoke
    return super().invoke(ctx)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/cli/main.py", line 475, in inner
    f(*iargs, **ikwargs)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/cli/deployment.py", line 139, in deploy_run_command
    deploy(
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/api/commands.py", line 478, in deploy
    model_meta = get_model_meta(model)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/api/utils.py", line 35, in get_model_meta
    model.load_value()
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/core/objects.py", line 830, in load_value
    self.model_type.load(self.relative_artifacts)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/core/model.py", line 277, in load
    self.model = self.io.load(artifacts)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/contrib/callable.py", line 89, in load
    refs[uuid] = io.load(ref_artifacts.get(uuid, {}))
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/contrib/torch.py", line 188, in load
    return load(f)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
  File "/Users/aguschin/Git/iterative/mlem-fly/.venv/lib/python3.9/site-packages/mlem/ext.py", line 256, in load_module
    module = importlib.import_module(fullname)
  File "/Users/aguschin/.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'transformers'
```

I guess it's connected with #525

**Comment by aguschin** [comment]
At the same time, `mlem --tb build docker -m ../mlem/emoji/lyrics2emoji --image.name lyrics2emoji --image.tag v1` works 🤷🏻‍♂️
