### ISSUE TITLE
Re-saving models that use custom code break

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#608]
Found this when adding MLEM to `example-get-started`. Looks like re-saving the same model tries to load code from script it sees in the same folder (`featurization.py`) instead of taking it from the `.mlem` model file. Error log:
```py
example-get-started-gto (add-mlem) $ python src/bug.py                                                                                    7.232s
Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/mlem/mlem/utils/module.py", line 456, in wrapper
    source = dill.source.getsource(obj)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/source.py", line 374, in getsource
    lines, lnum = getsourcelines(object, enclosing=enclosing)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/source.py", line 345, in getsourcelines
    code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/source.py", line 271, in getblocks
    lines, lnum = findsource(object)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/source.py", line 215, in findsource
    line = lines[lnum]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/example-get-started-gto/src/bug.py", line 5, in <module>
    save(
  File "/Users/aguschin/Git/iterative/mlem/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem/mlem/core/metadata.py", line 122, in save
    meta = get_object_metadata(
  File "/Users/aguschin/Git/iterative/mlem/mlem/core/metadata.py", line 53, in get_object_metadata
    return MlemModel.from_obj(
  File "/Users/aguschin/Git/iterative/mlem/mlem/core/objects.py", line 781, in from_obj
    mlem_model.add_processor(MAIN_PROCESSOR_NAME, mt)
  File "/Users/aguschin/Git/iterative/mlem/mlem/core/objects.py", line 805, in add_processor
    self.requirements += model_type.get_requirements().expanded
  File "/Users/aguschin/Git/iterative/mlem/mlem/core/model.py", line 341, in get_requirements
    ) + get_object_requirements(self.model)
  File "/Users/aguschin/Git/iterative/mlem/mlem/utils/module.py", line 641, in get_object_requirements
    a.dump(obj)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/Users/aguschin/.pyenv/versions/3.9.5/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/Users/aguschin/Git/iterative/mlem/mlem/utils/module.py", line 612, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.9/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.9.5/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/Git/iterative/mlem/mlem/utils/module.py", line 474, in wrapper
    raise Exception(
Exception: Cannot parse code for <function preprocess_texts at 0x132553820> from /Users/aguschin/Git/iterative/example-get-started-gto/src/featurization.py
```

Setting p1 since I think it can be a relatively frequent problem.

You can also repro this if you run `dvc repro`. Then saving in `src/train.py` will fail.

**Comment by aguschin** [comment]
The code is here https://github.com/aguschin/example-get-started/pull/2

**Comment by aguschin** [comment]
Ok, so as discussed with @mike0sv, it's because MLEM imports `preprocess_texts` func from `featurization.py`. Then Python executes the script in order to do the import, and since the script is not invoked with right args, that fails. I wonder if we could not dump the script as a whole, but instead do things recursively: if `preprocess_texts` needs something, we serialize it and only it. Then you wouldn't need to do `from featurization import preprocess_texts`.

For now I'll add `if __name__ == "__main__":` part to `example-get-started` in order to fix this. But in future we can try to do serialization in a smarter way if possible.

**Comment by aguschin** [comment]
Ok, I was trying to work around that. I ended up with this https://github.com/aguschin/example-get-started-mlem/pull/1, which still don't work:
```bash
$ dvc repro
...
Exception: Cannot parse code for <function preprocess_texts at 0x13f9aaf70> from /Users/aguschin/Git/iterative/example-gs/src/featurization.py
ERROR: failed to reproduce 'train': failed to run: python src/train.py data/prepared preprocessing model.pkl, exited with 1
```

see the script https://github.com/aguschin/example-get-started-mlem/blob/add-mlem/src/featurization.py
So, the problem, as I get it: now script has this structure:
```py
...
if __name__ == "__main__":
    bag_of_words = ...
    tfidf = ...
    def preprocess(x):
        return tfidf.transform(bag_of_words.transform(x))

    mlem.api.save(preprocess, "preprocessing", sample_data=texts)
```

and `save` fails due to `preprocess` being hidden in `if __name__ == "__main__"`. But! You can define `preprocess` only after you fitted `bag_of_words` and `tfidf`. So I just can't understand how one can use MLEM in this scenario now. We should come up with some decent workaround or fix this, I believe.

**Comment by aguschin** [comment]
Also, I just can't understand this well enough. If I save a custom model in a Jupyter notebook, will loading it re-run all the notebook, @mike0sv? This looks like a really unwanted behavior.

**Comment by mike0sv** [comment]
No, notebooks cannot be saved as a requirement. So, if it breaks, it will break either when you save custom code from the notebook (eg mlem cannot parse source code to create the requirement) or when you load the model (it will try to find code from the notebook but it isn't there)

**Comment by aguschin** [comment]
This may be resolved by `if __name__ == "__main__"` as discussed in #623, need to recheck

**Comment by aguschin** [comment]
@mike0sv btw was you able to TAL at https://github.com/aguschin/example-get-started-mlem/blob/add-mlem/src/featurization.py to maybe suggest how that should work best considering what's implemented in MLEM already?
