### ISSUE TITLE
Error when writing sources during building the docker environment

### ISSUE THREAD

**Issue by mattlbeck** [iterative/mlem#620]
Python==3.10, mlem==0.4.5

```
> mlem build --load docker_builder.mlem --model models/model
⏳️ Loading model from models/model.mlem
⏳️ Loading builder from docker_builder.mlem
💼 Adding model files...
🛠 Generating dockerfile...
💼 Adding sources...
❌ Unexpected error: a bytes-like object is required, not 'str'
```

Additional traceback:
```
Traceback (most recent call last):
  File "/home/mattlbeck/mambaforge/envs/mlem/bin/mlem", line 8, in <module>
    sys.exit(app())
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/cli/main.py", line 507, in inner
    f(*iargs, **ikwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/cli/main.py", line 370, in inner
    return f(*args, **kwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/cli/build.py", line 50, in build_load
    build(
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/api/commands.py", line 336, in build
    return builder.build(model)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/contrib/docker/base.py", line 570, in build
    ).build(obj)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/contrib/docker/base.py", line 545, in build
    docker_dir.write_distribution()
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/contrib/docker/context.py", line 324, in write_distribution
    self.write_local_sources(reqs)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/mlem/contrib/docker/context.py", line 402, in write_local_sources
    f.write(src)
  File "/home/mattlbeck/mambaforge/envs/mlem/lib/python3.10/site-packages/fsspec/implementations/local.py", line 352, in write
    return self.f.write(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mattlbeck** [comment]
Thanks @aguschin your fix works for me.

I'll message you on discord about sharing those files. Not sure of the best way to share those - the model itself is pretty big!
