### ISSUE TITLE
Error with relative imports during saving model with mlem

### ISSUE THREAD

**Issue by wiswisbus** [iterative/mlem#650]
I'm trying to save wav2vec2 model from [fairseq](https://github.com/facebookresearch/fairseq), but it seems that there's a bug in handling requirements with relative imports.

Versions
- mlem==0.4.10
- fairseq==0.12.2

Followings are the codes and the error log.

```bash
# Clone and install fairseq
git clone git@github.com:facebookresearch/fairseq.git
cd fairseq
pip install -e .
```

You can download checkpoints from [here](https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec#wav2vec-20)

Python script for saving wav2vec2

```python
from mlem.api import load, save

import fairseq

if __name__ == "__main__":

    wav2vec_ckpt_path = (
        "/Downloads/ckpts/wav2vec/xlsr2_300m.pt"
    )

    # Load Wav2Vec
    wav2vec, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task(
        [wav2vec_ckpt_path]
    )
    wav2vec = wav2vec[0]

    # Save
    save(wav2vec, "wav2vec")
```

<details>
<summary>Error log</summary>
<div markdown="1">

```
Traceback (most recent call last):
  File "debug.py", line 18, in <module>
    save(wav2vec, "wav2vec")
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/core/metadata.py", line 122, in save
    meta = get_object_metadata(
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/core/metadata.py", line 53, in get_object_metadata
    return MlemModel.from_obj(
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/core/objects.py", line 792, in from_obj
    mlem_model.add_processor(MAIN_PROCESSOR_NAME, mt)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/core/objects.py", line 816, in add_processor
    self.requirements += model_type.get_requirements().expanded
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/contrib/torch.py", line 229, in get_requirements
    return super().get_requirements() + InstallableRequirement.from_module(
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/core/model.py", line 341, in get_requirements
    ) + get_object_requirements(self.model)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 643, in get_object_requirements
    a.dump(obj)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 612, in save
    self.add_requirement(obj)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 591, in add_requirement
    self.add_requirement(local_req)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 591, in add_requirement
    self.add_requirement(local_req)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 591, in add_requirement
    self.add_requirement(local_req)
  [Previous line repeated 1 more time]
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 599, in add_requirement
    self.add_requirement(parent_package)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 591, in add_requirement
    self.add_requirement(local_req)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 588, in add_requirement
    for local_req in get_local_module_reqs(module):
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 355, in get_local_module_reqs
    result = [importing.import_module(i, p) for i, p in imports]
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/utils/module.py", line 355, in <listcomp>
    result = [importing.import_module(i, p) for i, p in imports]
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/site-packages/mlem/ext.py", line 265, in load_module
    module = importlib.import_module(fullname)
  File "/home/wis/anaconda3/envs/superhub_debug/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fairseq.data.audio.data_utils'
```

</div>
</details>

As shown in the error log, mlem tries to find `fairseq.data.audio.data_utils`. But as you can see [here](https://github.com/facebookresearch/fairseq/tree/main/fairseq/data/audio) there's no `data_utils` under `fairseq.data.audio`. 
I'm assuming that mlem is not handling properly with relative imports from this [part](https://github.com/facebookresearch/fairseq/blob/3f6ba43f07a6e9e2acf957fc24e57251a7a3f55c/fairseq/data/audio/raw_audio_dataset.py#L18).
It should import module `fairseq.data.data_utils` not the `fairseq.data.audio.data_utils`.

**Comment by aguschin** [comment]
Nice catch @wiswisbus! Would you like to investigate this and make a PR fixing this issue? I can help with reviewing and merging :)

**Comment by aguschin** [comment]
I also wonder if this happens with `pip install -e .` only, or `pip install github.com:facebookresearch/fairseq.git` (or whatever is the correct way to install it right from git) would work correctly.

**Comment by aminalaee** [comment]
I was taking a look into this and there are two points:
- Doing `pip install .` (removing -e editable) or pip install git+https or pip install fairseq solves the issues.
- I have prepared a fix, but specifically for `fairseq` it won't solve the issue because the project is using a vendored submodule `megatron`: https://github.com/facebookresearch/fairseq/tree/main/fairseq/model_parallel.

So is it worth the fix?

**Comment by aguschin** [comment]
@aminalaee I think the fix always worth it, don't hesitate to make a PR - especially if you already implemented it!

**Comment by aguschin** [comment]
Re megatron - I hope we can resolve that as well, since the version (commit) is pinned there. Once you make a PR I think I can TAL and see if I have any good ideas.

**Comment by aguschin** [comment]
@aminalaee, I'm having problems with reproducing issue with `megatron`. Could you please post a traceback so I could see what fails exactly?

**Comment by aminalaee** [comment]
@aguschin 
Here it is:

```python-traceback
Traceback (most recent call last):
  File "/path//mlem/example.py", line 18, in <module>
    save(wav2vec, "wav2vec")
  File "/path//mlem/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/path//mlem/mlem/core/metadata.py", line 122, in save
    meta = get_object_metadata(
  File "/path//mlem/mlem/core/metadata.py", line 53, in get_object_metadata
    return MlemModel.from_obj(
  File "/path//mlem/mlem/core/objects.py", line 792, in from_obj
    mlem_model.add_processor(MAIN_PROCESSOR_NAME, mt)
  File "/path//mlem/mlem/core/objects.py", line 816, in add_processor
    self.requirements += model_type.get_requirements().expanded
  File "/path//mlem/mlem/contrib/torch.py", line 229, in get_requirements
    return super().get_requirements() + InstallableRequirement.from_module(
  File "/path//mlem/mlem/core/model.py", line 341, in get_requirements
    ) + get_object_requirements(self.model)
  File "/path//mlem/mlem/utils/module.py", line 648, in get_object_requirements
    return a.to_requirements()
  File "/path//mlem/mlem/utils/module.py", line 553, in to_requirements
    r.add(CustomRequirement.from_module(mod))
  File "/path//mlem/mlem/core/requirements.py", line 236, in from_module
    raise ValueError(f"{mod} does not have __file__ attr")
ValueError: <module 'fairseq.model_parallel.megatron' (<_frozen_importlib_external._NamespaceLoader object at 0x7f3695152830>)> does not have __file__ attr
```

This was result of installing `fairseq` with `pip install -e .` and then running the `save` method in the issue example.

**Comment by aguschin** [comment]
Hmm. I assume this doesn't happen when doing `pip install fairseq`?

**Comment by aminalaee** [comment]
Yeah, it works well with `pip install fairseq`

**Comment by aguschin** [comment]
Ok, not sure how this can be fixed right now. @aminalaee, do you have any workaround in mind?

I also have 2 questions:
- @wiswisbus is this something that blocks your workflow? Do you absolutely need to install it with `-e`?
- @aminalaee would you like to contribute to this particular issue? Or you're just looking for something to contribute? There are a lot of good issues we can check out.

**Comment by aminalaee** [comment]
Yeah @aguschin I'll be happy to contribute to any issue that can help the project. Nothing specific really.

**Comment by wiswisbus** [comment]
Thank you! @aguschin @aminalaee 
I can work without installing package as editable mode. It might be better if it works with editable mode but it's not mandatory. Just didn't know that it only happens with editable mode. Thank you all again for the rapid response!

**Comment by aguschin** [comment]
Good to hear! Thank you @wiswisbus :)
